"""baseline full schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-14 01:33:51.722916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursing_services',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('duration_type', sa.String(length=20), nullable=True, comment='ENUM: Minutes, Hours, Days'),
    sa.Column('schedule_type', sa.String(length=20), nullable=False, comment='ENUM: Continuous, Daily_Shift'),
    sa.Column('shift_duration_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='ENUM: Patient, Nurse, Admin'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    # idx_addresses_location (GiST) is created automatically by GeoAlchemy2's
    # spatial_index=True listener when the addresses table is created.
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='e.g. booking_confirmed, policy_update'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audience_type', sa.String(length=10), nullable=False, comment='ENUM: global, role, user'),
    sa.Column('audience_role', sa.String(length=10), nullable=True, comment='ENUM: Patient, Nurse (only if audience_type=role)'),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('nurses',
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='ENUM: Male, Female, Other'),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('continuous_care_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('nurse_id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='ENUM: Male, Female, Other'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('blackout_dates',
    sa.Column('blackout_date_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blackout_date_id')
    )
    op.create_table('bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('parent_booking_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_parent_booking', sa.Boolean(), nullable=False),
    sa.Column('booking_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False, comment='ENUM: Pending, Confirmed, Completed, Cancelled, Rejected'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False, comment='ENUM: Pending, Paid, Refunded, Failed'),
    sa.Column('booking_address_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completion_otp', sa.String(length=6), nullable=True),
    sa.Column('completion_otp_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_address_id'], ['addresses.address_id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.ForeignKeyConstraint(['parent_booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['nursing_services.service_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('nurse_associated_services',
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['nursing_services.service_id'], ),
    sa.PrimaryKeyConstraint('nurse_id', 'service_id')
    )
    op.create_table('nurse_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='ENUM: Aadhar, PAN, NursingLicense, Other'),
    sa.Column('document_url', sa.String(length=255), nullable=False, comment='URL to the stored document (e.g., in an S3 bucket)'),
    sa.Column('verification_status', sa.String(length=20), nullable=False, comment='ENUM: Pending, Approved, Rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes from an admin regarding verification'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('working_hours',
    sa.Column('working_hours_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('working_hours_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False, comment='ENUM: Initiated, Success, Failed, Refunded'),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('refund_id', sa.String(length=255), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('gateway_order_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('working_hours')
    op.drop_table('nurse_documents')
    op.drop_table('nurse_associated_services')
    op.drop_table('bookings')
    op.drop_table('blackout_dates')
    op.drop_table('patients')
    op.drop_table('nurses')
    op.drop_table('notifications')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('nursing_services')
    # ### end Alembic commands ###
