"""added location column in address table to retrieve nurses within specific distance

Revision ID: 23935effe9e4
Revises: ce655b1b3ada
Create Date: 2026-03-16 02:30:54.351942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '23935effe9e4'
down_revision: Union[str, Sequence[str], None] = 'ce655b1b3ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.execute(
    "CREATE INDEX IF NOT EXISTS idx_addresses_location ON addresses USING gist(location)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_addresses_location', table_name='addresses', postgresql_using='gist')
    op.drop_column('addresses', 'location')
    # ### end Alembic commands ###
