"""Changes made on 27.08.25

Revision ID: 45910d2620a6
Revises: d76c7624036d
Create Date: 2025-08-27 10:45:27.220134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45910d2620a6'
down_revision: Union[str, Sequence[str], None] = 'd76c7624036d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='ENUM: Aadhar, PAN, NursingLicense, Other'),
    sa.Column('document_url', sa.String(length=255), nullable=False, comment='URL to the stored document (e.g., in an S3 bucket)'),
    sa.Column('verification_status', sa.String(length=20), nullable=False, comment='ENUM: Pending, Approved, Rejected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes from an admin regarding verification'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.alter_column('nurses', 'profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nurses', 'profile_picture_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('nurse_documents')
    # ### end Alembic commands ###
