"""Removed price from nurse_services table

Revision ID: 690e351fd44e
Revises: add_database_indexes
Create Date: 2026-04-11 18:02:24.554201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690e351fd44e'
down_revision: Union[str, Sequence[str], None] = 'add_database_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_city_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_availability_end_time'), table_name='availability')
    op.drop_index(op.f('ix_availability_is_booked'), table_name='availability')
    op.drop_index(op.f('ix_availability_nurse_booked'), table_name='availability')
    op.drop_index(op.f('ix_availability_nurse_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_nurse_time'), table_name='availability')
    op.drop_index(op.f('ix_availability_start_time'), table_name='availability')
    op.drop_index(op.f('ix_bookings_booking_address_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_nurse_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_nurse_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_patient_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_end_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status_time'), table_name='bookings')
    op.drop_index(op.f('ix_nurse_documents_nurse_id'), table_name='nurse_documents')
    op.drop_index(op.f('ix_nurse_documents_verification_status'), table_name='nurse_documents')
    op.drop_index(op.f('ix_nurse_services_service_id'), table_name='nurse_services')
    op.drop_column('nurse_services', 'price')
    op.alter_column('nurses', 'is_qualified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('nurses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_nurses_address_id'), table_name='nurses')
    op.drop_index(op.f('ix_nurses_is_active'), table_name='nurses')
    op.drop_index(op.f('ix_nurses_is_qualified'), table_name='nurses')
    op.drop_index(op.f('ix_nurses_is_verified'), table_name='nurses')
    op.drop_index(op.f('ix_nurses_verified_active'), table_name='nurses')
    op.drop_index(op.f('ix_patients_address_id'), table_name='patients')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_status'), table_name='payments')
    op.drop_index(op.f('ix_reviews_nurse_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_patient_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_review_date'), table_name='reviews')
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    op.drop_index(op.f('ix_services_is_qualified'), table_name='services')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_last_login_at'), table_name='users')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_index(op.f('ix_users_last_login_at'), 'users', ['last_login_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_is_qualified'), 'services', ['is_qualified'], unique=False)
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    op.create_index(op.f('ix_reviews_review_date'), 'reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_reviews_patient_id'), 'reviews', ['patient_id'], unique=False)
    op.create_index(op.f('ix_reviews_nurse_id'), 'reviews', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_status'), 'payments', ['payment_status'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_patient_status'), 'payments', ['patient_id', 'payment_status'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patients_address_id'), 'patients', ['address_id'], unique=False)
    op.create_index(op.f('ix_nurses_verified_active'), 'nurses', ['is_verified', 'is_active'], unique=False)
    op.create_index(op.f('ix_nurses_is_verified'), 'nurses', ['is_verified'], unique=False)
    op.create_index(op.f('ix_nurses_is_qualified'), 'nurses', ['is_qualified'], unique=False)
    op.create_index(op.f('ix_nurses_is_active'), 'nurses', ['is_active'], unique=False)
    op.create_index(op.f('ix_nurses_address_id'), 'nurses', ['address_id'], unique=False)
    op.alter_column('nurses', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('nurses', 'is_qualified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('nurse_services', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_nurse_services_service_id'), 'nurse_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_nurse_documents_verification_status'), 'nurse_documents', ['verification_status'], unique=False)
    op.create_index(op.f('ix_nurse_documents_nurse_id'), 'nurse_documents', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_bookings_status_time'), 'bookings', ['booking_status', 'scheduled_start_time'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_start_time'), 'bookings', ['scheduled_start_time'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_end_time'), 'bookings', ['scheduled_end_time'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status'), 'bookings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_bookings_patient_status'), 'bookings', ['patient_id', 'booking_status'], unique=False)
    op.create_index(op.f('ix_bookings_patient_id'), 'bookings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_bookings_nurse_status'), 'bookings', ['nurse_id', 'booking_status'], unique=False)
    op.create_index(op.f('ix_bookings_nurse_id'), 'bookings', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_bookings_booking_time'), 'bookings', ['booking_time'], unique=False)
    op.create_index(op.f('ix_bookings_booking_status'), 'bookings', ['booking_status'], unique=False)
    op.create_index(op.f('ix_bookings_booking_address_id'), 'bookings', ['booking_address_id'], unique=False)
    op.create_index(op.f('ix_availability_start_time'), 'availability', ['start_time'], unique=False)
    op.create_index(op.f('ix_availability_nurse_time'), 'availability', ['nurse_id', 'start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_availability_nurse_id'), 'availability', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_availability_nurse_booked'), 'availability', ['nurse_id', 'is_booked'], unique=False)
    op.create_index(op.f('ix_availability_is_booked'), 'availability', ['is_booked'], unique=False)
    op.create_index(op.f('ix_availability_end_time'), 'availability', ['end_time'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_index(op.f('ix_addresses_city_state'), 'addresses', ['city', 'state'], unique=False)
    # ### end Alembic commands ###
