"""nurse_services changed to nurse_associated_services

Revision ID: 811241c9f461
Revises: 79f915f97305
Create Date: 2026-05-28 16:37:36.129010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811241c9f461'
down_revision: Union[str, Sequence[str], None] = '79f915f97305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('nurse_services', 'nurse_associated_services')

    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('nurse_associated_services', 'nurse_services')

    # ### end Alembic commands ###
