"""nurse_services changed to nurse_associated_services

Revision ID: 811241c9f461
Revises: 79f915f97305
Create Date: 2026-05-28 16:37:36.129010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811241c9f461'
down_revision: Union[str, Sequence[str], None] = '79f915f97305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse_associated_services',
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['nursing_services.service_id'], ),
    sa.PrimaryKeyConstraint('nurse_id', 'service_id')
    )
    op.drop_table('spatial_ref_sys')
    op.drop_table('nurse_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nurse_services',
    sa.Column('nurse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], name=op.f('nurse_services_nurse_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['nursing_services.service_id'], name=op.f('nurse_services_service_id_fkey')),
    sa.PrimaryKeyConstraint('nurse_id', 'service_id', name=op.f('nurse_services_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('nurse_associated_services')
    # ### end Alembic commands ###
