"""Added working_hours and blackout_dates tables

Revision ID: 889c029914b9
Revises: 67199b98b760
Create Date: 2026-06-10 00:04:52.667611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '889c029914b9'
down_revision: Union[str, Sequence[str], None] = '67199b98b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    op.add_column('addresses', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.create_index('idx_addresses_location', 'addresses', ['location'], unique=False, postgresql_using='gist')
    op.add_column('bookings', sa.Column('parent_booking_id', sa.UUID(), nullable=True))
    op.create_table('working_hours',
        sa.Column('working_hours_id', sa.UUID(), nullable=False),
        sa.Column('nurse_id', sa.UUID(), sa.ForeignKey('nurses.nurse_id', ondelete='CASCADE'), nullable=False),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.Time(timezone=True), nullable=False),
        sa.Column('end_time', sa.Time(timezone=True), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.PrimaryKeyConstraint('working_hours_id', name=op.f('working_hours_pkey'))
    )
    op.create_table('blackout_dates',
        sa.Column('blackout_date_id', sa.UUID(), nullable=False),
        sa.Column('nurse_id', sa.UUID(), sa.ForeignKey('nurses.nurse_id', ondelete='CASCADE'), nullable=False),
        sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('blackout_date_id', name=op.f('blackout_dates_pkey'))
    )
    
    op.create_foreign_key(None, 'bookings', 'bookings', ['parent_booking_id'], ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blackout_dates')
    op.drop_table('working_hours')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'parent_booking_id')
    op.drop_index('idx_addresses_location', table_name='addresses', postgresql_using='gist')
    op.drop_column('addresses', 'location')
    op.create_table('availability',
        sa.Column('availability_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('nurse_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], name=op.f('availability_nurse_id_fkey')),
        sa.PrimaryKeyConstraint('availability_id', name=op.f('availability_pkey'))
    )
    # ### end Alembic commands ###
