"""Added working_hours and blackout_dates tables

Revision ID: 889c029914b9
Revises: 67199b98b760
Create Date: 2026-06-10 00:04:52.667611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '889c029914b9'
down_revision: Union[str, Sequence[str], None] = '67199b98b760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('nurse_services')
    op.drop_table('availability')
    op.add_column('addresses', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.create_index('idx_addresses_location', 'addresses', ['location'], unique=False, postgresql_using='gist')
    op.add_column('bookings', sa.Column('parent_booking_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('bookings_service_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'bookings', ['parent_booking_id'], ['booking_id'])
    op.create_foreign_key(None, 'bookings', 'nursing_services', ['service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_service_id_fkey'), 'bookings', 'services', ['service_id'], ['service_id'])
    op.drop_column('bookings', 'parent_booking_id')
    op.drop_index('idx_addresses_location', table_name='addresses', postgresql_using='gist')
    op.drop_column('addresses', 'location')
    op.create_table('availability',
    sa.Column('availability_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nurse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], name=op.f('availability_nurse_id_fkey')),
    sa.PrimaryKeyConstraint('availability_id', name=op.f('availability_pkey'))
    )
    op.create_table('nurse_services',
    sa.Column('nurse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.nurse_id'], name=op.f('nurse_services_nurse_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name=op.f('nurse_services_service_id_fkey')),
    sa.PrimaryKeyConstraint('nurse_id', 'service_id', name=op.f('nurse_services_pkey'))
    )
    op.create_table('services',
    sa.Column('service_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='ENUM: Minutes, Hours, Days'),
    sa.Column('is_qualified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('service_id', name=op.f('services_pkey')),
    sa.UniqueConstraint('service_name', name=op.f('services_service_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
