"""Changed services table to nursing_services and added new columns(is_continuous and shift_duration_hours) to differentiate continuous services 

Revision ID: ccae44bc4921
Revises: ce655b1b3ada
Create Date: 2026-05-26 14:08:08.703483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccae44bc4921'
down_revision: Union[str, Sequence[str], None] = 'ce655b1b3ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS nursing_services CASCADE")
    op.rename_table('services', 'nursing_services')
    op.add_column(
        'nursing_services',
        sa.Column('is_continuous', sa.Boolean(), nullable=True),
    )
    op.add_column(
        'nursing_services',
        sa.Column('shift_duration_hours', sa.Integer(), nullable=True),
    )
    op.drop_constraint(op.f('bookings_service_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(
        op.f('bookings_service_id_fkey'),
        'bookings',
        'nursing_services',
        ['service_id'],
        ['service_id'],
    )
    op.drop_constraint(op.f('nurse_services_service_id_fkey'), 'nurse_services', type_='foreignkey')
    op.create_foreign_key(
        op.f('nurse_services_service_id_fkey'),
        'nurse_services',
        'nursing_services',
        ['service_id'],
        ['service_id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('nurse_services_service_id_fkey'),
        'nurse_services',
        type_='foreignkey',
    )
    op.drop_constraint(
        op.f('bookings_service_id_fkey'),
        'bookings',
        type_='foreignkey',
    )
    op.execute(
        "ALTER TABLE nursing_services DROP COLUMN IF EXISTS shift_duration_hours"
    )
    op.execute("ALTER TABLE nursing_services DROP COLUMN IF EXISTS is_continuous")
    op.rename_table('nursing_services', 'services')
    op.create_foreign_key(
        op.f('nurse_services_service_id_fkey'),
        'nurse_services',
        'services',
        ['service_id'],
        ['service_id'],
    )
    op.create_foreign_key(
        op.f('bookings_service_id_fkey'),
        'bookings',
        'services',
        ['service_id'],
        ['service_id'],
    )
### end Alembic commands ###
