"""Modified the Nurse and Services table for writing services for Service table

Revision ID: ce655b1b3ada
Revises: 45910d2620a6
Create Date: 2025-09-27 13:59:01.741822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce655b1b3ada'
down_revision: Union[str, Sequence[str], None] = '45910d2620a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nurses', sa.Column('is_qualified', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('nurses', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('duration_type', sa.String(length=20), nullable=True, comment='ENUM: Minutes, Hours, Days'))
    op.add_column('services', sa.Column('is_qualified', sa.Boolean(), nullable=False, server_default='False'))
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('services', 'is_qualified')
    op.drop_column('services', 'duration_type')
    op.drop_column('services', 'duration')
    op.drop_column('nurses', 'is_active')
    op.drop_column('nurses', 'is_qualified')
    # ### end Alembic commands ###
